#!/usr/bin/env python3
"""
Convert a BDF bitmap font into a Braid-style embedded font atlas.

Usage:
    python3 bdf_to_braid_font.py <input.bdf> <output.h> [--name Name]

Output is a C++ header containing:
  - a license comment block copied from the BDF if found
  - the atlas as a flat R8Unorm image
  - a per-codepoint glyph table
  - cell / atlas / line-height constants

Assumptions (true for Cherry 13-r):
  - glyphs are monospaced or the caller is happy with a fixed cell size
  - codepoints are in 0..255 and packed into a 16x16 grid
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def parse_bdf(path: Path) -> Tuple[Dict[int, dict], int, int]:
    """Return glyphs, font_ascent, font_descent."""
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()

    font_ascent = 0
    font_descent = 0
    for line in lines:
        if line.startswith("FONT_ASCENT "):
            font_ascent = int(line.split()[1])
        elif line.startswith("FONT_DESCENT "):
            font_descent = int(line.split()[1])

    glyphs: Dict[int, dict] = {}
    i = 0
    n = len(lines)
    while i < n:
        if not lines[i].startswith("STARTCHAR"):
            i += 1
            continue

        encoding = None
        bbx = None
        bitmap_start = None
        j = i + 1
        while j < n and not lines[j].startswith("ENDCHAR"):
            if lines[j].startswith("ENCODING "):
                encoding = int(lines[j].split()[1])
            elif lines[j].startswith("BBX "):
                parts = lines[j].split()
                bbx = {
                    "w": int(parts[1]),
                    "h": int(parts[2]),
                    "xoff": int(parts[3]),
                    "yoff": int(parts[4]),
                }
            elif lines[j] == "BITMAP":
                bitmap_start = j + 1
            j += 1

        if encoding is None or bbx is None or bitmap_start is None:
            i = j + 1
            continue

        rows: List[int] = []
        for k in range(bitmap_start, j):
            if lines[k] == "ENDCHAR":
                break
            # Each pair of hex digits is one byte; width may span multiple bytes.
            hex_str = lines[k].strip()
            for byte_idx in range(0, len(hex_str), 2):
                rows.append(int(hex_str[byte_idx:byte_idx + 2], 16))

        # Pad or truncate rows to BBX height.
        while len(rows) < bbx["h"]:
            rows.append(0)
        rows = rows[:bbx["h"]]

        glyphs[encoding] = {
            "bbx": bbx,
            "rows": rows,
        }
        i = j + 1

    return glyphs, font_ascent, font_descent


def build_atlas(
    glyphs: Dict[int, dict],
    atlas_cols: int = 16,
    atlas_rows: int = 16,
) -> Tuple[bytearray, int, int, int, int]:
    """Pack glyphs into a byte-aligned atlas. Returns atlas bytes, aw, ah, cell_w, cell_h."""
    max_w = 0
    max_h = 0
    for g in glyphs.values():
        max_w = max(max_w, g["bbx"]["w"])
        max_h = max(max_h, g["bbx"]["h"])

    # Byte-align cell width; keep height as-is (GPU R8 format doesn't care).
    cell_w = ((max_w + 7) // 8) * 8
    cell_h = max_h
    atlas_w = cell_w * atlas_cols
    atlas_h = cell_h * atlas_rows

    atlas = bytearray(atlas_w * atlas_h)

    for cp, g in glyphs.items():
        if not (0 <= cp < atlas_cols * atlas_rows):
            continue
        bbx = g["bbx"]
        rows = g["rows"]
        cell_x = (cp % atlas_cols) * cell_w
        cell_y = (cp // atlas_cols) * cell_h

        # Place glyph at top-left of its cell. For fonts with positive yoff
        # (rare in our targets) we could shift it; Cherry's yoff is -2 and
        # aligns fine at the top.
        for r in range(bbx["h"]):
            row_byte = rows[r]
            for c in range(bbx["w"]):
                if (row_byte >> (7 - c)) & 1:
                    px = cell_x + c + bbx["xoff"]
                    py = cell_y + r
                    if 0 <= px < atlas_w and 0 <= py < atlas_h:
                        atlas[py * atlas_w + px] = 0xFF

    return atlas, atlas_w, atlas_h, cell_w, cell_h


def emit_header(
    glyphs: Dict[int, dict],
    atlas: bytearray,
    atlas_w: int,
    atlas_h: int,
    cell_w: int,
    cell_h: int,
    font_ascent: int,
    font_descent: int,
    out_path: Path,
    name: str,
    license_text: Optional[str],
) -> None:
    guard = f"BRAID_FONT_{name.upper()}_H"
    struct_name = f"BitmapFont{name}"

    lines: List[str] = []
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("// Generated by bdf_to_braid_font.py")
    lines.append("// Do not edit by hand.")
    lines.append("")
    if license_text:
        lines.append("/*")
        for lic_line in license_text.splitlines():
            lines.append(f" * {lic_line}".rstrip())
        lines.append(" */")
        lines.append("")

    lines.append("#include <cstdint>")
    lines.append("")

    # Metrics.
    line_height = font_ascent + font_descent
    lines.append(f"namespace braid::font::{name.lower()} {{")
    lines.append("")
    lines.append(f"constexpr int kAtlasWidth  = {atlas_w};")
    lines.append(f"constexpr int kAtlasHeight = {atlas_h};")
    lines.append(f"constexpr int kCellWidth   = {cell_w};")
    lines.append(f"constexpr int kCellHeight  = {cell_h};")
    lines.append(f"constexpr int kGlyphWidth  = {cell_w};   // advance for fixed-cell fonts")
    lines.append(f"constexpr int kGlyphHeight = {cell_h};")
    lines.append(f"constexpr int kLineHeight  = {line_height};")
    lines.append(f"constexpr int kAscent      = {font_ascent};")
    lines.append(f"constexpr int kDescent     = {font_descent};")
    lines.append("")

    # Glyph table.
    lines.append("struct Glyph {")
    lines.append("    uint16_t atlasX;")
    lines.append("    uint16_t atlasY;")
    lines.append("    uint8_t  width;")
    lines.append("    uint8_t  height;")
    lines.append("    int8_t   xoff;")
    lines.append("    int8_t   yoff;")
    lines.append("    uint8_t  advance;")
    lines.append("};")
    lines.append("")
    lines.append(f"constexpr Glyph kGlyphs[256] = {{")
    for cp in range(256):
        if cp in glyphs:
            g = glyphs[cp]
            bbx = g["bbx"]
            ax = (cp % 16) * cell_w
            ay = (cp // 16) * cell_h
            w = bbx["w"]
            h = bbx["h"]
            xoff = bbx["xoff"]
            yoff = bbx["yoff"]
            advance = cell_w  # fixed advance for now
        else:
            ax = ay = w = h = xoff = yoff = advance = 0
        lines.append(f"    {{{ax:3}, {ay:3}, {w:2}, {h:2}, {xoff:2}, {yoff:3}, {advance:2}}}, // U+{cp:04X}")
    lines.append("};")
    lines.append("")

    # Atlas bytes.
    lines.append(f"constexpr uint8_t kAtlas[{len(atlas)}] = {{")
    row_vals = []
    for i, b in enumerate(atlas):
        row_vals.append(f"0x{b:02X}")
        if (i + 1) % 16 == 0 or i == len(atlas) - 1:
            lines.append("    " + ", ".join(row_vals) + ",")
            row_vals = []
    lines.append("};")
    lines.append("")
    lines.append(f"}} // namespace braid::font::{name.lower()}")
    lines.append("")
    lines.append(f"#endif // {guard}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def extract_license(bdf_text: str) -> Optional[str]:
    """Try to grab a COPYRIGHT or LICENSE comment from the BDF header."""
    m = re.search(r"(?:COPYRIGHT|LICENSE)[ \t]+\"([^\"]+)\"", bdf_text, re.IGNORECASE)
    if m:
        return m.group(1)
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert a BDF font to a Braid C++ header")
    parser.add_argument("input", type=Path, help="Input .bdf file")
    parser.add_argument("output", type=Path, help="Output .h file")
    parser.add_argument("--name", default="Cherry13", help="C++ identifier name for the font")
    args = parser.parse_args()

    if not args.input.exists():
        print(f"error: {args.input} not found", file=sys.stderr)
        return 1

    glyphs, ascent, descent = parse_bdf(args.input)
    if not glyphs:
        print("error: no glyphs parsed", file=sys.stderr)
        return 1

    atlas, aw, ah, cw, ch = build_atlas(glyphs)
    license_text = extract_license(args.input.read_text(encoding="utf-8", errors="replace"))

    # Prefer a sibling LICENSE file (common upstream convention). Try a few
    # naming patterns so multiple fonts can coexist in one directory.
    license_candidates = [
        args.input.with_name("LICENSE"),
        args.input.with_name("LICENSE.txt"),
        args.input.with_name(f"LICENSE-{args.input.stem}"),
        args.input.with_name(f"{args.input.stem}-LICENSE"),
    ]
    for cand in license_candidates:
        if cand.exists():
            license_text = cand.read_text(encoding="utf-8", errors="replace").strip()
            break

    emit_header(
        glyphs, atlas, aw, ah, cw, ch,
        font_ascent=ascent,
        font_descent=descent,
        out_path=args.output,
        name=args.name,
        license_text=license_text,
    )

    print(f"wrote {args.output}: {aw}x{ah} atlas, {len(glyphs)} glyphs, cell {cw}x{ch}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
